// Copyright 2026 Aleutian AI
// SPDX-License-Identifier: Apache-2.0

package xwing

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"testing"

	"crypto/sha3"
)

// TestXWINGLabel verifies that label matches the IETF spec.
// Spec: XWingLabel = concat("\./", "/^\") = hex 5c2e2f2f5e5c (6 bytes).
func TestXWINGLabel(t *testing.T) {
	expected := []byte{0x5c, 0x2e, 0x2f, 0x2f, 0x5e, 0x5c}
	if !bytes.Equal(label, expected) {
		t.Errorf("label mismatch\n  got:  %x\n  want: %x", label, expected)
	}
	if len(label) != 6 {
		t.Errorf("label length: got %d, want 6", len(label))
	}
	// Verify ASCII interpretation: \.//^\
	// concat("\./", "/^\") = \. + / + / + ^ + \ = \.//^\
	ascii := "\\.//^\\"
	if string(label) != ascii {
		t.Errorf("label ASCII: got %q, want %q", string(label), ascii)
	}
}

// TestXWINGCombineFieldOrder verifies that combine uses the spec field order
// (draft-06: ss_M ‖ ss_X ‖ ct_X ‖ pk_X ‖ label — label LAST).
// This test independently computes SHA3-256 with known inputs and compares.
func TestXWINGCombineFieldOrder(t *testing.T) {
	// Use distinct 32-byte inputs so field-order bugs are detectable.
	ssM := bytes.Repeat([]byte{0x01}, 32)
	ssX := bytes.Repeat([]byte{0x02}, 32)
	ctX := bytes.Repeat([]byte{0x03}, 32)
	pkX := bytes.Repeat([]byte{0x04}, 32)

	// Compute expected SHA3-256 independently: ss_M ‖ ss_X ‖ ct_X ‖ pk_X ‖ label
	h := sha3.New256()
	h.Write(ssM)
	h.Write(ssX)
	h.Write(ctX)
	h.Write(pkX)
	h.Write(label) // label LAST
	expected := h.Sum(nil)

	got := combine(ssM, ssX, ctX, pkX)

	if !bytes.Equal(got[:], expected) {
		t.Errorf("combiner output mismatch (wrong field order?)\n  got:  %x\n  want: %x", got[:], expected)
	}

	// Verify that label-FIRST (draft-04 order) produces a DIFFERENT result.
	hWrong := sha3.New256()
	hWrong.Write(label) // label FIRST — wrong for draft-06
	hWrong.Write(ssM)
	hWrong.Write(ssX)
	hWrong.Write(ctX)
	hWrong.Write(pkX)
	wrongOrder := hWrong.Sum(nil)

	if bytes.Equal(got[:], wrongOrder) {
		t.Error("combiner output matches label-FIRST order; should use label-LAST (draft-06)")
	}
}

// TestXWINGKAT_Generate prints self-consistent KAT vectors to stdout.
// Run once with GENERATE_KAT=1 to populate testdata/xwing_kat.json.
// Not run during normal test execution.
//
// These are self-generated regression vectors, NOT IETF reference vectors.
// They verify internal consistency (encapsulate → decapsulate round-trip) and
// detect regressions in the combiner formula or wire format.
func TestXWINGKAT_Generate(t *testing.T) {
	if os.Getenv("GENERATE_KAT") == "" {
		t.Skip("set GENERATE_KAT=1 to generate test vectors")
	}

	type entry struct {
		Comment string `json:"_comment"`
		Seed    string `json:"seed"` // 32-byte XWING private key seed
		CT      string `json:"ct"`   // 1120-byte ciphertext (MLKEMCT ‖ X25519EPK)
		SS      string `json:"ss"`   // 32-byte expected shared secret
	}

	// Three fixed seeds built from sequential byte patterns.
	seeds := [][32]byte{
		func() [32]byte {
			var s [32]byte
			for i := range s {
				s[i] = 0x01 + byte(i)
			}
			return s
		}(),
		func() [32]byte {
			var s [32]byte
			for i := range s {
				s[i] = 0xa0 + byte(i)
			}
			return s
		}(),
		func() [32]byte {
			var s [32]byte
			for i := range s {
				s[i] = 0x51 + byte(i)
			}
			return s
		}(),
	}

	var entries []entry
	for i, seed := range seeds {
		func() {
			priv := PrivateKey{Seed: seed}
			defer priv.Zeroize()

			pub, err := priv.PublicKey()
			if err != nil {
				t.Fatalf("vector %d: derive public key: %v", i, err)
			}

			ct, ss, err := Encapsulate(pub)
			if err != nil {
				t.Fatalf("vector %d: encapsulate: %v", i, err)
			}
			defer ss.Zeroize()

			// Verify round-trip before recording.
			ss2, err := Decapsulate(ct, priv)
			if err != nil {
				t.Fatalf("vector %d: decapsulate verify: %v", i, err)
			}
			if ss != ss2 {
				t.Fatalf("vector %d: round-trip mismatch during generation", i)
			}

			// Serialize ciphertext in wire order: MLKEMCT ‖ X25519EPK
			ctBytes := make([]byte, 0, 1120)
			ctBytes = append(ctBytes, ct.MLKEMCT...)
			ctBytes = append(ctBytes, ct.X25519EPK...)

			entries = append(entries, entry{
				Comment: fmt.Sprintf("Vector %d — self-generated regression vector via TestXWINGKAT_Generate", i+1),
				Seed:    hex.EncodeToString(seed[:]),
				CT:      hex.EncodeToString(ctBytes),
				SS:      hex.EncodeToString(ss[:]),
			})
		}()
	}

	out, err := json.MarshalIndent(entries, "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}

	if err := os.WriteFile("testdata/xwing_kat.json", out, 0644); err != nil {
		t.Fatalf("write testdata/xwing_kat.json: %v", err)
	}
	t.Logf("wrote %d vectors to testdata/xwing_kat.json", len(entries))
}

// xwingKATVector is one entry from testdata/xwing_kat.json.
//
// Vectors are self-generated by TestXWINGKAT_Generate and round-trip verified
// (encapsulate with matching pub, then decapsulate, assert shared secrets match).
// They serve as regression vectors for the combiner formula and decapsulation path.
//
// Seed is the 32-byte XWING private key seed. CT and SS were produced by a real
// Encapsulate call against the corresponding public key; since Decapsulate
// is deterministic, these values are stable across runs.
//
// To regenerate: GENERATE_KAT=1 go test ./xwing/... -run TestXWINGKAT_Generate -v
type xwingKATVector struct {
	Seed string `json:"seed"` // hex, 32 bytes — XWING private key seed
	CT   string `json:"ct"`   // hex, 1120 bytes — ciphertext (MLKEMCT ‖ X25519EPK)
	SS   string `json:"ss"`   // hex, 32 bytes — expected shared secret
}

// TestXWINGKAT verifies Decapsulate against self-generated regression vectors.
//
// REGRESSION ONLY. These vectors were produced by this implementation, so they
// detect change, not error: a deviation from the specification that predates
// them is baked into them and passes here. Conformance is TestSpecVectors
// (official vectors, checksum-authenticated) plus the differential test against
// circl at the repository root. Do not cite this test as evidence of
// conformance, and do not regenerate these vectors to make a failure go away.
// For each vector, reconstructs the private key from the 32-byte seed, then
// decapsulates the ciphertext and asserts the shared secret matches.
//
// A minimum of 2 vectors must be present and pass.
func TestXWINGKAT(t *testing.T) {
	data, err := os.ReadFile("testdata/xwing_kat.json")
	if err != nil {
		t.Fatalf("read testdata/xwing_kat.json: %v", err)
	}
	var vectors []xwingKATVector
	if err := json.Unmarshal(data, &vectors); err != nil {
		t.Fatalf("unmarshal KAT vectors: %v", err)
	}
	if len(vectors) < 2 {
		t.Fatalf("need at least 2 KAT vectors, got %d", len(vectors))
	}

	for i, vec := range vectors {
		vec := vec
		t.Run(fmt.Sprintf("vector_%d", i), func(t *testing.T) {
			seedBytes, err := hex.DecodeString(vec.Seed)
			if err != nil {
				t.Fatalf("decode seed: %v", err)
			}
			if len(seedBytes) != 32 {
				t.Fatalf("seed: want 32 bytes, got %d", len(seedBytes))
			}

			ctBytes, err := hex.DecodeString(vec.CT)
			if err != nil {
				t.Fatalf("decode ct: %v", err)
			}
			if len(ctBytes) != 1120 {
				t.Fatalf("ct: want 1120 bytes, got %d", len(ctBytes))
			}

			expectedSS, err := hex.DecodeString(vec.SS)
			if err != nil {
				t.Fatalf("decode ss: %v", err)
			}
			if len(expectedSS) != 32 {
				t.Fatalf("ss: want 32 bytes, got %d", len(expectedSS))
			}

			priv, err := NewPrivateKey(seedBytes)
			if err != nil {
				t.Fatalf("NewPrivateKey: %v", err)
			}
			defer priv.Zeroize()

			// Wire format: MLKEMCT (1088B) ‖ X25519EPK (32B)
			ct := Ciphertext{
				MLKEMCT:   ctBytes[:1088],
				X25519EPK: ctBytes[1088:],
			}

			ss, err := Decapsulate(ct, priv)
			if err != nil {
				t.Fatalf("Decapsulate: %v", err)
			}
			defer ss.Zeroize()

			if !bytes.Equal(ss[:], expectedSS) {
				t.Errorf("shared secret mismatch\n  got prefix:  %x...\n  want prefix: %x...", ss[:4], expectedSS[:4])
			}
		})
	}
}

// TestXWINGRoundTrip verifies that encapsulate followed by decapsulate produces
// matching shared secrets.
func TestXWINGRoundTrip(t *testing.T) {
	pub, priv, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair: %v", err)
	}
	defer priv.Zeroize()

	ct, ss1, err := Encapsulate(pub)
	if err != nil {
		t.Fatalf("Encapsulate: %v", err)
	}
	defer ss1.Zeroize()

	ss2, err := Decapsulate(ct, priv)
	if err != nil {
		t.Fatalf("Decapsulate: %v", err)
	}
	defer ss2.Zeroize()

	if ss1 != ss2 {
		t.Errorf("shared secret mismatch: encapsulate prefix %x..., decapsulate prefix %x...", ss1[:4], ss2[:4])
	}
}

// TestXWINGWrongKey verifies that decapsulating with a different private key produces
// a different shared secret rather than an error. ML-KEM-768 uses implicit rejection
// (FIPS 203 §7.3): wrong-key decapsulation returns a pseudorandom value, not an error.
func TestXWINGWrongKey(t *testing.T) {
	pub1, _, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair (1): %v", err)
	}

	_, priv2, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair (2): %v", err)
	}
	defer priv2.Zeroize()

	ct, ss1, err := Encapsulate(pub1)
	if err != nil {
		t.Fatalf("Encapsulate: %v", err)
	}
	defer ss1.Zeroize()

	ss2, err := Decapsulate(ct, priv2)
	if err != nil {
		t.Fatalf("Decapsulate with wrong key returned unexpected error: %v", err)
	}
	defer ss2.Zeroize()

	if ss1 == ss2 {
		t.Error("wrong-key decapsulation produced the same shared secret (probability 2^-256)")
	}
}

// TestXWINGEncapsulate_InvalidPublicKey verifies that Encapsulate returns
// ErrInvalidPublicKey for all invalid public key inputs.
func TestXWINGEncapsulate_InvalidPublicKey(t *testing.T) {
	validPub, _, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair: %v", err)
	}

	cases := []struct {
		name string
		pub  PublicKey
	}{
		{"nil X25519Pub", PublicKey{X25519Pub: nil, MLKEMPub: validPub.MLKEMPub}},
		{"short X25519Pub", PublicKey{X25519Pub: make([]byte, 16), MLKEMPub: validPub.MLKEMPub}},
		{"nil MLKEMPub", PublicKey{X25519Pub: validPub.X25519Pub, MLKEMPub: nil}},
		{"short MLKEMPub", PublicKey{X25519Pub: validPub.X25519Pub, MLKEMPub: make([]byte, 100)}},
		{"both nil", PublicKey{}},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			_, _, err := Encapsulate(tc.pub)
			if err != ErrInvalidPublicKey {
				t.Errorf("want ErrInvalidPublicKey, got %v", err)
			}
		})
	}
}

// TestXWINGDecapsulate_InvalidCiphertext verifies that Decapsulate returns
// ErrInvalidCiphertext for all invalid ciphertext inputs.
func TestXWINGDecapsulate_InvalidCiphertext(t *testing.T) {
	pub, priv, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair: %v", err)
	}
	defer priv.Zeroize()

	validCT, ss, err := Encapsulate(pub)
	if err != nil {
		t.Fatalf("Encapsulate: %v", err)
	}
	defer ss.Zeroize()

	cases := []struct {
		name string
		ct   Ciphertext
	}{
		{"nil MLKEMCT", Ciphertext{MLKEMCT: nil, X25519EPK: validCT.X25519EPK}},
		{"short MLKEMCT", Ciphertext{MLKEMCT: make([]byte, 100), X25519EPK: validCT.X25519EPK}},
		{"nil X25519EPK", Ciphertext{MLKEMCT: validCT.MLKEMCT, X25519EPK: nil}},
		{"short X25519EPK", Ciphertext{MLKEMCT: validCT.MLKEMCT, X25519EPK: make([]byte, 16)}},
		{"both nil", Ciphertext{}},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			_, err := Decapsulate(tc.ct, priv)
			if err != ErrInvalidCiphertext {
				t.Errorf("want ErrInvalidCiphertext, got %v", err)
			}
		})
	}
}

// TestXWINGMarshalBinary_RoundTrip verifies that MarshalBinary and UnmarshalPublicKey
// are inverses of each other, and that the wire format is MLKEMPub ‖ X25519Pub.
func TestXWINGMarshalBinary_RoundTrip(t *testing.T) {
	pub, _, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair: %v", err)
	}

	encoded, err := pub.MarshalBinary()
	if err != nil {
		t.Fatalf("MarshalBinary: %v", err)
	}
	if len(encoded) != 1216 {
		t.Fatalf("MarshalBinary: want 1216 bytes, got %d", len(encoded))
	}

	// Verify wire order: first 1184 bytes = MLKEMPub, last 32 bytes = X25519Pub
	if !bytes.Equal(encoded[:1184], pub.MLKEMPub) {
		t.Error("wire format: first 1184 bytes should be MLKEMPub")
	}
	if !bytes.Equal(encoded[1184:], pub.X25519Pub) {
		t.Error("wire format: last 32 bytes should be X25519Pub")
	}

	recovered, err := UnmarshalPublicKey(encoded)
	if err != nil {
		t.Fatalf("UnmarshalPublicKey: %v", err)
	}

	if !bytes.Equal(pub.X25519Pub, recovered.X25519Pub) {
		t.Errorf("X25519Pub mismatch after round-trip")
	}
	if !bytes.Equal(pub.MLKEMPub, recovered.MLKEMPub) {
		t.Errorf("MLKEMPub mismatch after round-trip")
	}
}

// TestXWINGMarshalBinary_InvalidInputs verifies MarshalBinary error cases.
func TestXWINGMarshalBinary_InvalidInputs(t *testing.T) {
	validPub, _, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair: %v", err)
	}

	cases := []struct {
		name string
		pub  PublicKey
	}{
		{"nil MLKEMPub", PublicKey{MLKEMPub: nil, X25519Pub: validPub.X25519Pub}},
		{"short MLKEMPub", PublicKey{MLKEMPub: make([]byte, 100), X25519Pub: validPub.X25519Pub}},
		{"nil X25519Pub", PublicKey{MLKEMPub: validPub.MLKEMPub, X25519Pub: nil}},
		{"short X25519Pub", PublicKey{MLKEMPub: validPub.MLKEMPub, X25519Pub: make([]byte, 16)}},
		{"both nil", PublicKey{}},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			_, err := tc.pub.MarshalBinary()
			if err != ErrInvalidPublicKey {
				t.Errorf("want ErrInvalidPublicKey, got %v", err)
			}
		})
	}
}

// TestXWINGUnmarshalPublicKey_InvalidInputs verifies UnmarshalPublicKey error cases.
func TestXWINGUnmarshalPublicKey_InvalidInputs(t *testing.T) {
	cases := []struct {
		name string
		data []byte
	}{
		{"nil", nil},
		{"empty", []byte{}},
		{"too short", make([]byte, 1215)},
		{"too long", make([]byte, 1217)},
		{"way too short", make([]byte, 32)},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			_, err := UnmarshalPublicKey(tc.data)
			if err != ErrInvalidPublicKey {
				t.Errorf("want ErrInvalidPublicKey, got %v", err)
			}
		})
	}
}

// TestXWINGUnmarshalPublicKey_IndependentCopy verifies that UnmarshalPublicKey
// returns independent copies (not aliases of the input buffer).
func TestXWINGUnmarshalPublicKey_IndependentCopy(t *testing.T) {
	pub, _, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair: %v", err)
	}
	encoded, err := pub.MarshalBinary()
	if err != nil {
		t.Fatalf("MarshalBinary: %v", err)
	}

	recovered, err := UnmarshalPublicKey(encoded)
	if err != nil {
		t.Fatalf("UnmarshalPublicKey: %v", err)
	}

	// Mutate the original encoded buffer.
	for i := range encoded {
		encoded[i] = 0xff
	}

	// Recovered key should be unaffected.
	if !bytes.Equal(pub.MLKEMPub, recovered.MLKEMPub) {
		t.Error("MLKEMPub changed after mutating input buffer — not an independent copy")
	}
	if !bytes.Equal(pub.X25519Pub, recovered.X25519Pub) {
		t.Error("X25519Pub changed after mutating input buffer — not an independent copy")
	}
}

// TestXWINGNewPrivateKey_InvalidInputs verifies NewPrivateKey error cases.
func TestXWINGNewPrivateKey_InvalidInputs(t *testing.T) {
	cases := []struct {
		name string
		seed []byte
	}{
		{"nil", nil},
		{"empty", []byte{}},
		{"too short", make([]byte, 31)},
		{"too long", make([]byte, 33)},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			_, err := NewPrivateKey(tc.seed)
			if err != ErrInvalidPrivateKey {
				t.Errorf("want ErrInvalidPrivateKey, got %v", err)
			}
		})
	}
}

// TestXWINGZeroize_PrivateKey verifies that Zeroize zeroes the seed of an PrivateKey.
func TestXWINGZeroize_PrivateKey(t *testing.T) {
	_, priv, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair: %v", err)
	}

	// Confirm there are non-zero bytes before zeroizing.
	allZero := true
	for _, b := range priv.Seed {
		if b != 0 {
			allZero = false
			break
		}
	}
	if allZero {
		t.Fatal("Seed is all-zero before Zeroize (test precondition failed)")
	}

	priv.Zeroize()

	for i, b := range priv.Seed {
		if b != 0 {
			t.Errorf("Seed[%d] = %d after Zeroize, want 0", i, b)
		}
	}
}

// TestXWINGZeroize_SharedSecret verifies that Zeroize zeroes all bytes of a SharedSecret.
func TestXWINGZeroize_SharedSecret(t *testing.T) {
	pub, priv, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair: %v", err)
	}
	defer priv.Zeroize()

	_, ss, err := Encapsulate(pub)
	if err != nil {
		t.Fatalf("Encapsulate: %v", err)
	}

	allZero := true
	for _, b := range ss {
		if b != 0 {
			allZero = false
			break
		}
	}
	if allZero {
		t.Fatal("SharedSecret is all-zero before Zeroize (test precondition failed)")
	}

	ss.Zeroize()

	for i, b := range ss {
		if b != 0 {
			t.Errorf("SharedSecret[%d] = %d after Zeroize, want 0", i, b)
		}
	}
}

// TestXWINGPublicKey_Derivation verifies that PublicKey() derives the correct public
// key from a seed (round-trip: generate → derive pub → encapsulate → decapsulate).
func TestXWINGPublicKey_Derivation(t *testing.T) {
	pub1, priv, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair: %v", err)
	}
	defer priv.Zeroize()

	pub2, err := priv.PublicKey()
	if err != nil {
		t.Fatalf("PublicKey: %v", err)
	}

	if !bytes.Equal(pub1.X25519Pub, pub2.X25519Pub) {
		t.Error("X25519Pub mismatch between GenerateKeyPair and PublicKey")
	}
	if !bytes.Equal(pub1.MLKEMPub, pub2.MLKEMPub) {
		t.Error("MLKEMPub mismatch between GenerateKeyPair and PublicKey")
	}
}

// TestXWINGStringer_Redaction verifies that String() and GoString() do not leak
// key material for PrivateKey and SharedSecret.
func TestXWINGStringer_Redaction(t *testing.T) {
	_, priv, err := GenerateKeyPair()
	if err != nil {
		t.Fatalf("GenerateKeyPair: %v", err)
	}
	defer priv.Zeroize()

	if s := priv.String(); s != "[REDACTED PrivateKey]" {
		t.Errorf("PrivateKey.String() = %q, want redacted", s)
	}
	if s := priv.GoString(); s != "[REDACTED PrivateKey]" {
		t.Errorf("PrivateKey.GoString() = %q, want redacted", s)
	}

	var ss SharedSecret
	ss[0] = 0x42
	if s := ss.String(); s != "[REDACTED SharedSecret]" {
		t.Errorf("SharedSecret.String() = %q, want redacted", s)
	}
	if s := ss.GoString(); s != "[REDACTED SharedSecret]" {
		t.Errorf("SharedSecret.GoString() = %q, want redacted", s)
	}

	// Verify fmt.Sprintf doesn't leak bytes.
	formatted := fmt.Sprintf("%v", priv)
	if formatted != "[REDACTED PrivateKey]" {
		t.Errorf("fmt.Sprintf(%%v, priv) = %q, want redacted", formatted)
	}
}

// TestXWINGExpandDecapsulationKey verifies that SHAKE256 expansion produces
// deterministic output from the same seed.
func TestXWINGExpandDecapsulationKey(t *testing.T) {
	var seed [32]byte
	for i := range seed {
		seed[i] = byte(i)
	}

	mlkemSeed1, x25519Priv1 := expandDecapsulationKey(seed)
	mlkemSeed2, x25519Priv2 := expandDecapsulationKey(seed)

	if mlkemSeed1 != mlkemSeed2 {
		t.Error("SHAKE256 expansion not deterministic for mlkemSeed")
	}
	if x25519Priv1 != x25519Priv2 {
		t.Error("SHAKE256 expansion not deterministic for x25519Priv")
	}

	// Different seeds must produce different output.
	var seed2 [32]byte
	seed2[0] = 0xff
	mlkemSeed3, x25519Priv3 := expandDecapsulationKey(seed2)

	if mlkemSeed1 == mlkemSeed3 {
		t.Error("different seeds produced same mlkemSeed")
	}
	if x25519Priv1 == x25519Priv3 {
		t.Error("different seeds produced same x25519Priv")
	}
}
